### ISSUE TITLE
Lego Boost Control manual control reverse does not work

### ISSUE THREAD

**Issue by TWCunningham** [ttu/lego-boost-app#14]
Using the Lego Boost Control activated from the Android home screen icon, manual control reverse does not work, but using legoboostdev does work.  Is there any way to either fix the release version or have the home screen icon point to legoboostdev?

**Comment by ttu** [comment]
Thanks for reporting the issue!

Unfortunately I can't test the site myself, as at the moment I don't have access to a functional Lego Boost. I updated the latest version to legoboostdev. If you can test that manual control in legoboostdev works, I can then release that version.

**Comment by TWCunningham** [comment]
Interesting.  The reverse works now, but you have to hold the forward and reverse buttons to keep the robot going.  So you don’t really need the stop button in the middle.  Also, the left and right, if held, will keep turning (not just 90 degrees), which is cool.  I think I like not having to hold forward and reverse, because then you can press left or right, the robot turns, and continues forward or backward.  And of course then you need the stop button. 😊  Thanks for letting me try that out!

Take care,

Tom

**Comment by ttu** [comment]
Hi! Thanks for testing this out.

There is a selector under Manual Extra Control, where you can define Click mode or Arcade mode. That selection defines how controls work. I have to admin that usability really hasn't been the main focus and I ended up with an "engineer UI", where I have millions of buttons spread to different views 😄

I will release a new version soon 👍

**Comment by TWCunningham** [comment]
Oh yeah, I see now, I had it switched to Arcade mode but didn’t make the connection between the modes and the controls (duh).  So now I’ve switched between Click and Arcade and see the operational difference, very cool!  I think your UI is fine, and the no-install Web interface is fantastic.  Thanks for getting me straightened out!

Take care,

Tom

**Comment by ttu** [comment]
New version released
